services:
  - type: web
    name: cloud-storage
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: |
      chmod +x mvnw
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/cloud-storage-*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: cloud-storage-db
          property: connectionString
